//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFbase.Classes
{
    using System;
    using System.Collections.Generic;

    public partial class Workers : System.ComponentModel.INotifyPropertyChanged
    {

        #region Implement INotifyPropertyChanged

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public Workers() { }

        public Workers(string name, Departments dep)
        {
            FIO = name;
            if (dep == null)
            {
                Department = null;
            }
            else
            {
                Department = dep.Id;
            }
        }

        protected virtual void OnPropertyChanged(string propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        #endregion
        private int _Id;
        public int Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    _Id = value;
                    OnPropertyChanged("Id");
                }
            }
        }

        private string _FIO;
        public string FIO
        {
            get
            {
                return _FIO;
            }
            set
            {
                if (_FIO != value)
                {
                    _FIO = value;
                    OnPropertyChanged("FIO");
                }
            }
        }

        private Nullable<int> _Department;
        public Nullable<int> Department
        {
            get
            {
                return _Department;
            }
            set
            {
                if (_Department != value)
                {
                    _Department = value;
                    OnPropertyChanged("Department");
                }
            }
        }

    }
}
